apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: online-boutique
  labels:
    app: cartservice
spec:
  selector:
    matchLabels:
      app: cartservice
  replicas: 1
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: server
          image: DOCKERHUB_REPO/cartservice:latest
          ports:
            - containerPort: 7070
          env:
            - name: REDIS_ADDR
              value: "redis-cart:6379"
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:7070"
          readinessProbe:
            tcpSocket:
              port: 7070
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 7070
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: online-boutique
spec:
  selector:
    app: cartservice
  ports:
    - port: 7070
      targetPort: 7070
