apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: online-boutique
  labels:
    app: currencyservice
spec:
  selector:
    matchLabels:
      app: currencyservice
  replicas: 1
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
        - name: server
          image: DOCKERHUB_REPO/currencyservice:latest
          ports:
            - containerPort: 7000
          env:
            - name: PORT
              value: "7000"
            - name: DISABLE_STATS
              value: "1"
            - name: DISABLE_TRACING
              value: "1"
          readinessProbe:
            tcpSocket:
              port: 7000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 7000
            initialDelaySeconds: 15
            periodSeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: online-boutique
spec:
  selector:
    app: currencyservice
  ports:
    - port: 7000
      targetPort: 7000
